site_name: Docs | IMPulse
docs_dir: content

theme:
  name: material
  favicon: img/favicon.ico
  logo: logo.svg
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - toc.follow
extra:
  analytics:
    provider: google
    property: G-LL3R99ZZGW
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 2-6
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/custom.css

nav:
- index.md
- Integrations:
  - mattermost.md
  - slack.md
  - telegram.md
- IMPulse Server:
  - installation.md
  - Configuration:
    - alertmanager.md
    - envs.md
    - config_file.md
  - Features:
    - google.md
    - ui.md
  - concepts.md
  - versioning.md
- Workflow:
  - best.md
  - howto.md
