site_name: Docs | IMPulse
docs_dir: content

theme:
  name: material
  favicon: img/favicon.ico
  logo: logo.svg
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - toc.follow
extra:
  analytics:
    provider: google
    property: G-LL3R99ZZGW
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 2-6
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/custom.css

nav:
- index.md
- IMPULSE SERVER:
  - installation.md
  - Configuration:
    - envs.md
    - impulse.yml: config_file.md
  - Features:
    - api.md
    - buttons.md
    - check.md
    - ha.md
    - special_variables.md
    - templates.md
    - ui.md
  - Concepts:
    - concepts/basics.md
    - concepts/incident.md
    - concepts/messengers.md
  - versioning.md
- INTEGRATIONS:
  - Alert Sources:
    - alertmanager.md
    - grafana.md
  - Messengers:
    - integrations/messengers/mattermost.md
    - integrations/messengers/slack.md
    - integrations/messengers/telegram.md
  - Scheduling:
    - integrations/calendars/google.md
  - Task Management:
    - integrations/task_management/jira.md
  - External Notifications:
    - integrations/external/instatus.md
    - integrations/external/telegram.md
    - integrations/external/twilio.md
    - integrations/external/zvonok.md
