name: test

concurrency:
  group: ${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'only "test" is supported'
        required: true
        default: 'test'
      messenger:
        description: 'slack, mattermost or telegram'
        required: false
        default: 'slack'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Recreate IMPulse
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/impulse/${{ github.event.inputs.environment }}

            docker-compose down
            rm -rf /opt/impulse/${{ github.event.inputs.environment }}/data/incidents

            cd /opt/impulse/${{ github.event.inputs.environment }}/config
            ln -sf impulse.yml."${{ github.event.inputs.messenger }}" impulse.yml
            
            cd /opt/impulse/${{ github.event.inputs.environment }}
            docker-compose pull
            docker-compose up -d
