name: develop

concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches:
    - 'develop'
    tags:
    - 'v*'
    - '0.0.1'
    - '0.0.2'
    - '0.0.3'
    - '0.0.4'
    - '0.0.5'
    - '0.0.6'
    - '0.0.7'
    - '0.0.8'
    - '0.0.9'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  # Helm
  OWNER: eslupmi
  TARGET_REPO: helm-charts
  TARGET_BRANCH: main
  TARGET_DIR: packages
  PUBLISH_BASE_URL: https://eslupmi.github.io/packages

jobs:
  # build-and-push-image:
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:

  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Log in to the Container registry
  #     uses: docker/login-action@v3
  #     with:
  #       registry: ${{ env.REGISTRY }}
  #       username: ${{ github.actor }}
  #       password: ${{ secrets.GITHUB_TOKEN }}

  #   - name: Extract metadata (tags, labels) for Docker
  #     id: meta
  #     uses: docker/metadata-action@v5
  #     with:
  #       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  #   - name: Build Docker image
  #     run: docker build .

  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v5
  #     with:
  #       context: .
  #       push: true
  #       tags: ${{ steps.meta.outputs.tags }}
  #       labels: ${{ steps.meta.outputs.labels }}

  publish-helm-charts:
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Package charts from ./helm
        run: |
          mkdir -p packaged
          if [ -f "helm/Chart.yaml" ]; then
            echo ">> Updating chart version and appVersion to ${{ github.ref_name }}"
            sed -i "s/%VERSION%/${{ github.ref_name }}/g" helm/Chart.yaml
            echo ">> Packaging helm chart"
            helm dependency update helm/ || true
            helm package helm/ -d packaged
          else
            echo "No Chart.yaml found in helm/ directory"
            exit 1
          fi
          ls -l packaged

      - name: Checkout helm-charts repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.OWNER }}/${{ env.TARGET_REPO }}
          ref: ${{ env.TARGET_BRANCH }}
          token: ${{ secrets.HELM_TOKEN }}
          path: helm-charts-repo

      - name: Copy packaged chart to helm-charts repository
        run: |
          mkdir helm-charts-repo/${{ env.TARGET_DIR }}/
          cp packaged/*.tgz helm-charts-repo/${{ env.TARGET_DIR }}/
          cd helm-charts-repo/${{ env.TARGET_DIR }}
          helm repo index . --url ${{ env.PUBLISH_BASE_URL }}

      - name: Commit and push to helm-charts repository
        run: |
          cd helm-charts-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.TARGET_DIR }}/
          git commit -m "Update helm chart: ${{ github.ref_name }}" || exit 0
          git push