name: test

concurrency:
  group: ${{ github.ref }}

on:
  workflow_dispatch:
    inputs:
      messenger:
        description: 'slack, mattermost or telegram'
        required: false
        default: 'slack'

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: test
    steps:
      - name: Recreate IMPulse
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/impulse/test

            docker-compose down
            rm -rf /opt/impulse/test/data/incidents

            cp config/impulse.yml."${{ github.event.inputs.messenger }}" config/impulse.yml
            docker-compose pull
            docker-compose up -d
